<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Афиша ВК КиТ ВГИК");
?> 
<p> 
  <table width="1020" height="30" cellspacing="1" cellpadding="0" border="0" align="center" style="border-collapse: collapse;"> 
    <tbody> 
      <tr><td width="" height="25" bgcolor="#9d0a0f"> 
          <p align="center"><font face="Verdana"><strong><font color="#fdc68c"><font size="5">РАСПИСАНИЕ НА 2011 год</font></font></strong></font></p>
         </td></tr>
     </tbody>
   </table>
 
  <br />
 </p>
 
<p> 
  <br />
 </p>
 <em><strong><font face="Georgia"><font size="2"> </font></font></strong></em><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> </font></font> 
<table width="800" cellspacing="1" cellpadding="1" border="3" bgcolor="#790000" align="center" borderclolor=""> 
  <tbody> 
    <tr align="center"><td width="50" height="25"><font face="Verdana"><font size="2"><font color="#cccccc"><strong>Дата</strong></font></font></font></td><td width="90" height=""><font face="Verdana"><font size="2"><font color="#cccccc"><strong>День недели</strong></font></font></font></td><td width="50" height=""><font face="Verdana"><font size="2"><font color="#cccccc"><strong>Время</strong></font></font></font></td><td width="160" height=""><font face="Verdana"><font size="2"><font color="#cccccc"><strong>Спектакль</strong></font></font></font></td><td width="130" height=""><font face="Verdana"><font size="2"><font color="#cccccc"><strong>Автор</strong></font></font></font></td><td width="220" height=""><font face="Verdana"><font size="2"><font color="#cccccc"><strong>Площадка</strong></font></font></font></td></tr>
   
    <tr align="center"><td width="" height="35" bgcolor="#f7977a" colspan="6"><font face="Verdana"><font size="3"><strong>АПРЕЛЬ</strong></font></font></td></tr>
   
    <tr><td width="" valign="middle" height="30" align="center" colspan="1"><font face="Verdana"><strong><font size="2"><font color="#ebebeb">2</font></font></strong></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font></td><td colspan="1"><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center" colspan="1"><font face="Verdana"><strong><font size="2"><font color="#ebebeb">4</font></font></strong></font></td><td rowspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">понедельник</font></font></font></td><td rowspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td rowspan="1"><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a></td><td rowspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font><font face="Verdana"><font size="2"></font></font></td><td width="" height="" bgcolor="" rowspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">Театр &quot;Эрмитаж&quot; (ул. Каретный Ряд, д. 3, стр. 1) Вход по пригласительным билетам.</font></font></font></td></tr>
   
    <tr><td width="" valign="middle" height="40" align="center" colspan="1"><font face="Verdana"><strong><font size="2"><font color="#ebebeb">9</font></font></strong></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">18-00</font></font></font></td><td colspan="1"><font face="Verdana"><font size="2"> </font></font> 
        <p><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><font face="Verdana"><font size="2"><font color="#ebebeb">*</font></font></font><font color="#9d0a0f"><font face="Verdana"><font size="2"> </font></font></font> 
          <br />
         <font color="#ebebeb"><font face="Verdana"><font size="2">*в спектакле  </font></font><font face="Verdana"><font size="2"> 
                <br />
               </font></font><font face="Verdana"><font size="2"> вместе со студентами </font></font><font face="Verdana"><font size="2"> 
                <br />
               </font></font><font face="Verdana"><font size="2"> принимает участие </font></font><font face="Verdana"><font size="2"> 
                <br />
               </font></font><font face="Verdana"><font size="2"> мастер &mdash; В.Н.&nbsp;Шиловский</font></font></font><font color="#9d0a0f"><font face="Verdana"><font size="2"> </font></font><font face="Verdana"><font size="2"> 
                <br />
               </font></font><font face="Verdana"><font size="2"> </font></font></font></p>
       <font face="Verdana"><font size="2"> </font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ЦДРИ (Пушечная ул., дом 9/6)</font></font></font></td></tr>
   
    <tr><td width="" valign="middle" height="30" align="center" colspan="1"><font face="Verdana"><strong><font size="2"><font color="#ebebeb">16</font></font></strong></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td align="center" colspan="1"><font face="Verdana"><font size="2"><strong><font color="#ffffff">23</font></strong></font></font></td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font> </td><td colspan="1"> <a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font> </td></tr>
   
    <tr><td align="center" colspan="1"><font face="Verdana"><font size="2"><font color="#ffffff"><strong>25</strong></font></font></font></td><td colspan="1"><font face="Verdana"><font color="#ffffff"><font size="2">понедельник</font></font></font></td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font> </td><td colspan="1"> <a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">Московский Академический театр им.Вл.Маяковского (Филиал на Сретенке)</font></font></font></td></tr>
   
    <tr><td align="center" colspan="1"><strong><font color="#ffffff"><font face="Verdana"><font size="2">30</font></font></font></strong></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ffffff">суббота</font></font></font></td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font> </td><td colspan="1"> <a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font> </td><td colspan="1"> <font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font> </td></tr>
   
    <tr align="center"><td width="" height="35" bgcolor="#9d0a0f" colspan="6"><font face="Verdana"><font size="3"><strong>МАРТ</strong></font></font></td></tr>
   
    <tr><td width="" height="30" align="center" colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">5</font></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font><font face="Verdana"><font size="2"></font></font></td><td width="" height="" colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center" colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">12</font></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td colspan="1"><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a></td><td colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font></td><td width="" height="" colspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr align="center"><td width="" height="35" bgcolor="#9d0a0f" colspan="6"><font face="Verdana"><font size="3"><strong>ФЕВРАЛЬ</strong></font></font></td></tr>
   
    <tr><td width="" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">26</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" ><font face="Verdana"><font size="2"> </font></font></a></td><td width="" height=""><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font><font face="Verdana"><font size="2"> </font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">19</font></font></font></td><td width="" height=""><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Папа в паутине</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/papa_v_pautine.php" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">Р. Куни</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">5</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">суббота</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font></td><td width="" height=""><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">2</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">среда</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font></td><td width="" height=""><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr><td width="" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">1</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">вторник</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">20-00</font></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" ><font face="Verdana"><font size="2"> </font></font></a></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font></td><td rowspan="1"><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font></td></tr>
   
    <tr align="center"><td width="" height="35" bgcolor="#9d0a0f" colspan="6"><font face="Verdana"><font size="3"><strong>ЯНВАРЬ</strong></font></font></td></tr>
   
    <tr><td width="" valign="middle" height="30" align="center"><font face="Verdana"><font size="2"><font color="#ebebeb">31</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">понедельник</font></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">19-00</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><a href="http://www.vgik.info/highcourses/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"><u>Доходное место</u></font></strong></font></font></a><a href="http://www.vgik.info/cdpo/works/shilovskiy2011/dohodnoe_mesto.php" title="Посмотреть" target="_blank" ><font face="Verdana"><font size="2"><strong><font color="#fff799"></font></strong></font></font></a><font face="Verdana"><font size="2"> </font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">А.Н. Островский</font></font></font><font face="Verdana"><font size="2"></font></font></td><td><font face="Verdana"><font size="2"><font color="#ebebeb">ВК КиТ</font></font></font><font face="Verdana"><font size="2"><font color="#ebebeb">, ауд. №217 (Будайская ул., д. 3)</font></font></font> </td></tr>
   </tbody>
 </table>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>