<?
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["pub"]["14"]="T_8";
$PERM["upload"]["14"]="T_8";
$PERM["upload"]["10"]="W";
$PERM["/"]["*"]="R";
$PERM["library"]["13"]="X";
$PERM["college"]["12"]="X";
$PERM["college"]["8"]="W";
$PERM["bitrix"]["10"]="W";
$PERM["recruitmentagency"]["4"]="X";
$PERM["auth"]["2"]="D";
$PERM["auth"]["3"]="R";
?>