<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("װמעמאכüבמל");
?>  <?$APPLICATION->IncludeComponent(
	"bitrix:photogallery_user",
	"",
	Array(
		"INDEX_PAGE_TOP_ELEMENTS_COUNT" => "40",
		"SHOW_ONLY_PUBLIC" => "N",
		"USE_LIGHT_TEMPLATE" => "N",
		"WATERMARK" => "Y",
		"WATERMARK_COLORS" => array("FFFFFF"),
		"USE_LIGHT_VIEW" => "Y",
		"IBLOCK_TYPE" => "INTENATIONAL",
		"IBLOCK_ID" => "82",
		"GALLERY_GROUPS" => array("1"),
		"ONLY_ONE_GALLERY" => "Y",
		"MODERATION" => "Y",
		"SECTION_SORT_BY" => array("UF_DATE"),
		"SECTION_SORT_ORD" => "DESC",
		"ELEMENT_SORT_FIELD" => "id",
		"ELEMENT_SORT_ORDER" => "desc",
		"SEF_MODE" => "N",
		"SECTION_PAGE_ELEMENTS" => "15",
		"ELEMENTS_PAGE_ELEMENTS" => "50",
		"PAGE_NAVIGATION_TEMPLATE" => "",
		"ELEMENTS_USE_DESC_PAGE" => "Y",
		"DATE_TIME_FORMAT_SECTION" => "d.m.Y",
		"DATE_TIME_FORMAT_DETAIL" => "d.m.Y",
		"UPLOAD_MAX_FILE_SIZE" => "5M",
		"GALLERY_AVATAR_SIZE" => "50",
		"ALBUM_PHOTO_THUMBS_SIZE" => "150",
		"ALBUM_PHOTO_SIZE" => "150",
		"THUMBS_SIZE" => "200",
		"PREVIEW_SIZE" => "500",
		"ORIGINAL_SIZE" => "0",
		"JPEG_QUALITY1" => "95",
		"JPEG_QUALITY2" => "95",
		"JPEG_QUALITY" => "90",
		"ADDITIONAL_SIGHTS" => array(),
		"WATERMARK_MIN_PICTURE_SIZE" => "800",
		"PATH_TO_FONT" => array(""),
		"WATERMARK_RULES" => "USER",
		"USE_RATING" => "Y",
		"SHOW_TAGS" => "N",
		"DISPLAY_PANEL" => "N",
		"SET_TITLE" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"MAX_VOTE" => "5",
		"VOTE_NAMES" => array("1","2","3","4","5"),
		"DISPLAY_AS_RATING" => "rating",
		"USE_COMMENTS" => "N",
		"ANALIZE_SOCNET_PERMISSION" => "N",
		"VARIABLE_ALIASES" => Array(
			"USER_ID" => "USER_ID",
			"USER_ALIAS" => "USER_ALIAS",
			"SECTION_ID" => "SECTION_ID",
			"ELEMENT_ID" => "ELEMENT_ID",
			"PAGE_NAME" => "PAGE_NAME",
			"ACTION" => "ACTION"
		)
	),
false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>